name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: beevelop/android-nodejs:latest  # A Docker image with Android SDK and Node.js

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y python3-pip libssl-dev libffi-dev
          pip3 install --upgrade pip
          pip3 install cython
          pip3 install buildozer

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('currency-converter-kivy-app/buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('currency-converter-kivy-app/buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          cd currency-converter-kivy-app
          buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: currency-converter-kivy-app/bin
