name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev libffi-dev openjdk-8-jdk git unzip wget

          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$PATH:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3

          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip -d $ANDROID_HOME
          echo "y" | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30"

          sudo apt-get install -y build-essential
          sudo apt-get install -y cmake pkg-config libboost-python-dev libboost-thread-dev libboost-system-dev liblog4cpp5-dev

          mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools/
          cd $HOME/.buildozer/android/platform/android-sdk/build-tools/
          wget https://dl.google.com/android/repository/build-tools_r30.0.3-linux.zip
          unzip build-tools_r30.0.3-linux.zip
          mv android-11 $ANDROID_HOME/build-tools/30.0.3

          sudo apt-get install -y aidl

          pip3 install --user cython buildozer

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          $HOME/.local/bin/buildozer android debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin
