name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Set up environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libssl-dev libffi-dev git unzip wget libboost-python-dev libboost-thread-dev libboost-system-dev liblog4cpp5-dev cmake pkg-config build-essential

          mkdir -p $HOME/cmdline-tools
          wget -qO- https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip | bsdtar -xvf- -C $HOME/cmdline-tools
          export ANDROID_SDK_ROOT=$HOME/cmdline-tools
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --install "build-tools;33.0.2" "platforms;android-31"
          yes | sdkmanager --licenses




      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u "+%Y%m%d")" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('src/buildozer.spec') }}
          
      - name: Install Buildozer
        run: pip3 install --user buildozer
        
      - name: Install Cython
        run: pip3 install --user cython

      - name: Build APK
        run: |
          cd src
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: src/bin/*.apk
